// This file is automatically generated and contains assets from sei.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x3894085Ef7Ff0f0aeDf52E2A2704928d1Ec074F1');
export const USDT_ADDRESS = Address.fromString('0xB75D0B03c06A926e488e2659DF1A861F860bD3d1');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x3894085Ef7Ff0f0aeDf52E2A2704928d1Ec074F1'), // USDC
    Address.fromString('0xB75D0B03c06A926e488e2659DF1A861F860bD3d1'), // USDT
  ],
  pricingAssets: [
    Address.fromString('0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7'), // WSEI
    Address.fromString('0xDD7d5e4Ea2125d43C16eEd8f1FFeFffa2F4b4aF6'), // JLY
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
